### PR TITLE
WEB-1179 fix Dockerfile for local dev

### PR DESCRIPTION
**Pull request by pzelnip**
As it turns out the base docker image used (the "onbuild" variant) is
now deprecated and recommended to not be used.  See:

https://hub.docker.com/_/ruby/

https://github.com/docker-library/official-images/issues/2076

I found with the 2.3-onbuild image I'd get failure to even complete
the first line of the Dockerfile on a docker build.  This replaces
the onbuild image with a proper Ruby 2.3 image and modifies the
instructions for running as appropriate.

### CODE REVIEW

**Comment by pzelnip** [comment]
If a reviewer has a Windows box to test the Docker commands on that'd be great.  I'm currently downloading a Windows VM from modern.ie & will test the Docker stuff on that, but wouldn't mind an extra sanity check.

**Comment by pzelnip** [comment]
FWIW, I tested this (by building the Docker image & running the server) on:

- my Mac running OSX Sierra
- a Ubuntu 16 VM

Both worked.  I did find an Ubuntu 14 VM failed, but given Ubuntu 14 is no longer in LTS I'm not super concerned about that.

I also pulled down a Windows 10 VM from modern.ie.  I installed Docker into that, and got numerous errors.  Doing some googling seemed to suggest switching to "Windows Containers" in Docker.  I tried that and error went away, but then running the command to build the dev docs Docker image and got another error:

```
Step 1/9 : FROM ruby:2.3
2.3: Pulling from library/ruby
no matching manifest for windows/amd64 in the manifest list entries
```

I then googled and found this: https://stackoverflow.com/questions/39720254/can-i-run-docker-in-a-virtual-machine which seems to indicate getting Docker working on a Windows VM is...non-trivial.

Shrug.

**Comment by Lmasniuk** [comment]
I have confirmed that it is possible to build and run this project on a windows machine with the updated docker run command

**Comment by pzelnip** [comment]
Whoops my bad, changed to the test branch, though IIRC the test branch has diverged from master (ie I think there's stuff on test that hasn't yet made it to master).  Lemme know if you want me to change the base branch to something else.

**Comment by pzelnip** [comment]
This needs to be revised as it turns out the deployment uses the same dockerfile and will fail with this current change.

I will revise, but in the meantime *do not merge this*

**Comment by pzelnip** [comment]
Fixed the dependencies.  Context: the build job runs ```docker run -e ONBOARDING_HOST=${ONBOARDING_HOST} -v $APP_HOME/build:/usr/src/app/build dev.bambora.com static``` to generate the static content to be deployed.  My change from yesterday fixed the local dev environment, but broke the ```static``` command as a result of broken transitive dependencies.  The most recent commit fixes that by updating the related dependencies that needed to be updated as a result of updating ```nokogiri```.

I have tested these changes by:

* running the dev server local command on my Mac
* running the dev server local command on an Ubuntu 16 VM
* running the static (build the site) command on my Mac
* running the static (build the site) command on a Ubuntu 16 VM

All worked as expected.

**Comment by pzelnip** [comment]
As per discussion in standup this morning, I've changed the base branch of this PR to be careless-whisper as it's in sync with master, whereas the test branch is currently out of sync (there's changes that are on test that are not on master).

Once merged, this should get autodeployed by bamboo to http://dev.beanstream.com.careless-whisper.s3-website-us-east-1.amazonaws.com

**Comment by pzelnip** [comment]
Built & deployed to http://dev.beanstream.com.careless-whisper.s3-website-us-east-1.amazonaws.com/

**Pull request merged**
